#!/bin/bash
nro_proc=`grep Nro_clientes ambiente.in | cut -d " " -f 2`

make clean > /dev/null
make > /dev/null
java Servidor&
for i in `seq 1 $nro_proc`
do
    pos=`expr $i + 1`;
    nom_maquinas=`grep Maquinas ambiente.in | cut -d " " -f $pos`
    px=`grep Processos ambiente.in | cut -d " " -f $pos`
    scp $px.class $nom_maquinas: > /dev/null
    scp file.txt $nom_maquinas: > /dev/null
    #echo 'ssh' $nom_maquinas 'java' $px
    ssh $nom_maquinas java $px < file.txt
    #echo 'ssh' $nom_maquinas 'rm -f' $px'.class'
    ssh $nom_maquinas rm -f $px.class >/dev/null
done
