compile:
	javac Main.java

run:
	java Main 5 < input.in

all: compile run

clean:
	rm -rf *.class


# A saída do sistema deve ser a descrição dos eventos (L: local, S: send, R: receive) e seu respectivo timestamp.
# Os fontes devem conter um Makefile (inspirem-se nos outros arquivos da disciplina), um README (com instruções de uso)
# e devem executar, obrigatoriamente, na plataforma de desenvolvimento da disciplina (ens1).

